Repository fkdl0048/23_1_Capstone, pull requests merged in 2023-05, with the labels that each got.

#24 [Feat] : 상대방 집 방문 기능 추가
  CapStone/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  CapStone/Assets/Resources/ArtResource/assets/character/player.prefab
  CapStone/Assets/Resources/ArtResource/assets/character/player_controller.cs
  CapStone/Assets/Resources/PhotonTest/Player.prefab
  CapStone/Assets/Resources/Prefabs/UI/VisitBtn.prefab
  CapStone/Assets/Resources/Prefabs/UI/VisitBtn.prefab.meta
  CapStone/Assets/Scenes/Test/PUN Test.unity
  CapStone/Assets/Scripts/Runtime/Managers/GameManager.cs
  CapStone/Assets/Scripts/Runtime/Managers/PlayerManager.cs
  CapStone/Assets/Scripts/Runtime/Managers/PlayerManager.cs.meta
  CapStone/Assets/Scripts/Tests/PhotonTest.cs
  CapStone/Assets/Scripts/Tests/PlayerPhoton.cs
  CapStone/Assets/Scripts/Tests/PlayerPhoton.cs.meta
Labels: minseok, Feat

#32 Feature/UI model
  CapStone/Assets/Prefabs/UI/Title/LoginCanvas.prefab
  CapStone/Assets/Resources/Prefabs/UI/DefalutPopup.prefab
  CapStone/Assets/Resources/Prefabs/UI/DefalutPopup.prefab.meta
  CapStone/Assets/Resources/Prefabs/UI/GameView.prefab
  CapStone/Assets/Resources/Prefabs/UI/GameView.prefab.meta
  CapStone/Assets/Resources/Prefabs/UI/InputPopup.prefab
  CapStone/Assets/Resources/Prefabs/UI/InputPopup.prefab.meta
  CapStone/Assets/Resources/Prefabs/UI/MainMenuView.prefab
  CapStone/Assets/Resources/Prefabs/UI/MainMenuView.prefab.meta
  CapStone/Assets/Resources/Prefabs/UI/VisitBtn.prefab
  CapStone/Assets/Resources/Prefabs/UI/WarningToolTip.prefab
  CapStone/Assets/Resources/free.meta
  CapStone/Assets/Resources/free/assets.meta
  CapStone/Assets/Resources/free/assets/housing.meta
  CapStone/Assets/Resources/free/assets/housing/house_doors.png.meta
  CapStone/Assets/Resources/free/assets/housing/house_interiors_assets.png.meta
  CapStone/Assets/Resources/free/assets/housing/housing_system_roofs.png.meta
  CapStone/Assets/Resources/free/assets/tileset.meta
  CapStone/Assets/Resources/free/assets/tileset/outside_assets_stairs.png.meta
  CapStone/Assets/Scenes/Flow.meta
  CapStone/Assets/Scenes/Flow/Game.unity
  CapStone/Assets/Scenes/Flow/Game.unity.meta
  CapStone/Assets/Scenes/Flow/MainMenu.unity
  CapStone/Assets/Scenes/Flow/MainMenu.unity.meta
  CapStone/Assets/Scripts/Runtime/Managers/GameManager.cs
  CapStone/Assets/Scripts/Runtime/Managers/PlayfabManager.cs
  CapStone/Assets/Scripts/Runtime/Managers/UIManager.cs
  CapStone/Assets/Scripts/Runtime/PlayFab/LoginPlayer.cs
  CapStone/Assets/Scripts/Runtime/PlayFab/RegisterPlayer.cs
  CapStone/Assets/Scripts/Runtime/UI/Controller.meta
  CapStone/Assets/Scripts/Runtime/UI/Controller/GameUIController.cs
  CapStone/Assets/Scripts/Runtime/UI/Controller/GameUIController.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/Controller/MainMenuUIController.cs
  CapStone/Assets/Scripts/Runtime/UI/Controller/MainMenuUIController.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/Model.meta
  CapStone/Assets/Scripts/Runtime/UI/Model/UINavigation.cs
  CapStone/Assets/Scripts/Runtime/UI/Model/UINavigation.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/Model/UIView.cs
  CapStone/Assets/Scripts/Runtime/UI/Model/UIView.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/Popup.meta
  CapStone/Assets/Scripts/Runtime/UI/Popup/DefalutPopup.cs
  CapStone/Assets/Scripts/Runtime/UI/Popup/DefalutPopup.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/Popup/InputPopup.cs
  CapStone/Assets/Scripts/Runtime/UI/Popup/InputPopup.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/ToolTip/NotiToolTip.cs
  CapStone/Assets/Scripts/Runtime/UI/ToolTip/WarningToolTip.cs
  CapStone/Assets/Scripts/Runtime/UI/View.meta
  CapStone/Assets/Scripts/Runtime/UI/View/GameUIView.cs
  CapStone/Assets/Scripts/Runtime/UI/View/GameUIView.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/View/MainMenuUIView.cs
  CapStone/Assets/Scripts/Runtime/UI/View/MainMenuUIView.cs.meta
  CapStone/ProjectSettings/EditorBuildSettings.asset
Labels: Feat

#46 Feature/economy system
  CapStone/Assets/Resources/BasicUIResources/assets/card_system/cards.png.meta
  CapStone/Assets/Resources/BasicUIResources/assets/ui_banners/banners_horizontal.png.meta
  CapStone/Assets/Resources/BasicUIResources/assets/ui_grids/grids.png.meta
  CapStone/Assets/Resources/BasicUIResources/assets/ui_windows/windows.png.meta
  CapStone/Assets/Resources/Prefabs/UI/GameView.prefab
  CapStone/Assets/Resources/Prefabs/UI/InputPopup.prefab
  CapStone/Assets/Resources/Prefabs/UI/InventoryItem.prefab
  CapStone/Assets/Resources/Prefabs/UI/InventoryItem.prefab.meta
  CapStone/Assets/Resources/Prefabs/UI/InventoryPopup.prefab
  CapStone/Assets/Resources/Prefabs/UI/InventoryPopup.prefab.meta
  CapStone/Assets/Resources/Prefabs/UI/MainMenuView.prefab
  CapStone/Assets/Resources/Sprite.meta
  CapStone/Assets/Resources/Sprite/Item.meta
  CapStone/Assets/Resources/Sprite/Item/HardWood.png
  CapStone/Assets/Resources/Sprite/Item/HardWood.png.meta
  CapStone/Assets/Scenes/Flow/Game.unity
  CapStone/Assets/Scripts/Runtime/Managers/DataManager.cs
  CapStone/Assets/Scripts/Runtime/Managers/GameManager.cs
  CapStone/Assets/Scripts/Runtime/Managers/UIManager.cs
  CapStone/Assets/Scripts/Runtime/UI/Controller/GameUIController.cs
  CapStone/Assets/Scripts/Runtime/UI/Controller/MainMenuUIController.cs
  CapStone/Assets/Scripts/Runtime/UI/Popup/InventoryItem.cs
  CapStone/Assets/Scripts/Runtime/UI/Popup/InventoryItem.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/Popup/InventoryPopup.cs
  CapStone/Assets/Scripts/Runtime/UI/Popup/InventoryPopup.cs.meta
  CapStone/Assets/Scripts/Runtime/UI/View/GameUIView.cs
  CapStone/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  CapStone/Assets/test.cs
  CapStone/Assets/test.cs.meta
  GameFlow.md
Labels: Feat

#50 [Feat] : OX 퀴즈 오류 수정
  .DS_Store
  CapStone/Assets/Scripts/Runtime/Managers/PlayerManager.cs
  CapStone/Assets/Scripts/Runtime/MultiPlay/OXQuiz.cs
  CapStone/Assets/Scripts/Tests/PhotonTest.cs
  CapStone/ProjectSettings/EditorBuildSettings.asset
Labels: minseok, Feat, Fix

#57 [Feat] : photonManager 수정
  .DS_Store
  CapStone/Assets/Scripts/Runtime/Managers/PhotonManager.cs
  CapStone/Assets/Scripts/Runtime/SinglePlay/player_controller.cs
Labels: minseok, Feat
